import FreeSimpleGUI as sc
# label=sc.Text('type in a todo')
# input_box=sc.InputText(tooltip='enter a todo')
# button=sc.Button('add')
# window=sc.Window('My todo App',layout=[[label],[input_box,button]])
# window.read()
# window.close()
label=sc.Text('enter feet')
label2=sc.Text('enter inches')
input_box=sc.InputText(tooltip='enter feet')
input_box2=sc.InputText(tooltip='enter inches')
button=sc.Button('convert')
window=sc.Window('converter',layout=[[label,input_box],[label2,input_box2],[button]])
window.read()
window.close()